// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TMAnimeLight","status":true,"description":"イベントにアニメーション付きの明かりを表示します。","parameters":{"range":"0.1","defaultZ":"4","frames":"30"}}
];
